local toggles = require 'rosavim.config.toggles'

return {
  enabled = true,
  hidden = toggles.get 'picker_hidden',
  ignored = toggles.get 'picker_ignored',
  layout = { preset = toggles.get 'picker_layout', preview = toggles.get 'picker_preview', border = toggles.get 'picker_border' },
  sources = {
    files = {
      hidden = toggles.get 'picker_hidden',
      ignored = toggles.get 'picker_ignored',
    },
    explorer = {
      finder = 'explorer',
      diagnostics = true,
      diagnostics_open = false,
      layout = { layout = { position = toggles.get 'explorer_right' and 'right' or 'left', width = 34 }, preview = false },
      focus = 'list',
      auto_close = false,
      git_untracked = true,
      git_status_open = false,
    },
    -- Hide third-party / generated code so :Snacks.picker.todo_comments() only
    -- surfaces TODO/WARN/NOTE comments written by the user, not those from libs.
    todo_comments = {
      hidden = false,
      ignored = false,
      exclude = {
        '**/node_modules/**',
        '**/bower_components/**',
        '**/__pycache__/**',
        '**/.venv/**',
        '**/venv/**',
        '**/env/**',
        '**/site-packages/**',
        '**/.tox/**',
        '**/vendor/**',
        '**/dist/**',
        '**/build/**',
        '**/out/**',
        '**/target/**',
        '**/.next/**',
        '**/.nuxt/**',
        '**/.svelte-kit/**',
        '**/.turbo/**',
        '**/.cache/**',
        '**/.parcel-cache/**',
        '**/coverage/**',
        '**/.git/**',
        '**/.idea/**',
        '**/.gradle/**',
        '**/.mvn/**',
        '**/Pods/**',
        '**/DerivedData/**',
        '**/*.min.js',
        '**/*.min.css',
        '**/*.map',
        '**/*.lock',
        '**/package-lock.json',
        '**/yarn.lock',
        '**/pnpm-lock.yaml',
        '**/bun.lockb',
        '**/composer.lock',
        '**/Cargo.lock',
        '**/poetry.lock',
      },
    },
  },
  styles = {
    enabled = true,
  },
  win = {
    input = {
      keys = {
        ['<C-h>'] = { 'toggle_hidden', mode = { 'i', 'n' } },
        ['<C-l>'] = { 'toggle_ignored', mode = { 'i', 'n' } },
      },
    },
    list = {
      keys = {
        ['<C-h>'] = { 'toggle_hidden', mode = { 'i', 'n' } },
        ['<C-l>'] = { 'toggle_ignored', mode = { 'i', 'n' } },
      },
    },
  },
  icons = {
    files = {
      enabled = true,
      dir = ' ',
      dir_open = '󰝰 ',
      file = ' ',
      test_dir = ' ',
    },
    diagnostics = {
      Error = ' ',
      Warn = ' ',
      Hint = ' ',
      Info = ' ',
    },
    lsp = {
      unavailable = '',
      enabled = ' ',
      disabled = ' ',
      attached = '󰖩 ',
    },
    kinds = {
      Array = ' ',
      Boolean = '󰨙 ',
      Class = ' ',
      Color = ' ',
      Control = ' ',
      Collapsed = ' ',
      Constant = '󰏿 ',
      Constructor = ' ',
      Copilot = ' ',
      Enum = ' ',
      EnumMember = ' ',
      Event = ' ',
      Field = ' ',
      File = ' ',
      Folder = ' ',
      Function = '󰊕 ',
      Interface = ' ',
      Key = ' ',
      Keyword = ' ',
      Method = '󰊕 ',
      Module = ' ',
      Namespace = '󰦮 ',
      Null = ' ',
      Number = '󰎠 ',
      Object = ' ',
      Operator = ' ',
      Package = ' ',
      Property = ' ',
      Reference = ' ',
      Snippet = '󱄽 ',
      String = ' ',
      Struct = '󰆼 ',
      Text = ' ',
      TypeParameter = ' ',
      Unit = ' ',
      Unknown = ' ',
      Value = ' ',
      Variable = '󰀫 ',
    },
  },
}
