return {
  enabled = true,
  hidden = false,
  ignored = true,
  layout = { preset = 'default', preview = true, border = 'rounded' },
  sources = {
    files = {
      hidden = false,
      ignored = false,
    },
    explorer = {
      finder = 'explorer',
      diagnostics = true,
      diagnostics_open = false,
      layout = { layout = { position = 'left', width = 34 }, preview = false },
      focus = 'list',
      auto_close = false,
      git_untracked = true,
      git_status_open = false,
    },
  },
  styles = {
    enabled = true,
  },
  win = {
    input = {
      keys = {
        ['<C-h>'] = { 'toggle_hidden', mode = { 'i', 'n' } },
        ['<C-l>'] = { 'toggle_ignored', mode = { 'i', 'n' } },
      },
    },
    list = {
      keys = {
        ['<C-h>'] = { 'toggle_hidden', mode = { 'i', 'n' } },
        ['<C-l>'] = { 'toggle_ignored', mode = { 'i', 'n' } },
      },
    },
  },
  icons = {
    files = {
      enabled = true,
      dir = ' ',
      dir_open = ' ',
      file = ' ',
      test_dir = ' ',
    },
    diagnostics = {
      Error = ' ',
      Warn = ' ',
      Hint = ' ',
      Info = ' ',
    },
    lsp = {
      unavailable = '',
      enabled = ' ',
      disabled = ' ',
      attached = '󰖩 ',
    },
    kinds = {
      Array = ' ',
      Boolean = '󰨙 ',
      Class = ' ',
      Color = ' ',
      Control = ' ',
      Collapsed = ' ',
      Constant = '󰏿 ',
      Constructor = ' ',
      Copilot = ' ',
      Enum = ' ',
      EnumMember = ' ',
      Event = ' ',
      Field = ' ',
      File = ' ',
      Folder = ' ',
      Function = '󰊕 ',
      Interface = ' ',
      Key = ' ',
      Keyword = ' ',
      Method = '󰊕 ',
      Module = ' ',
      Namespace = '󰦮 ',
      Null = ' ',
      Number = '󰎠 ',
      Object = ' ',
      Operator = ' ',
      Package = ' ',
      Property = ' ',
      Reference = ' ',
      Snippet = '󱄽 ',
      String = ' ',
      Struct = '󰆼 ',
      Text = ' ',
      TypeParameter = ' ',
      Unit = ' ',
      Unknown = ' ',
      Value = ' ',
      Variable = '󰀫 ',
    },
  },
}
