local M = {}

local toggles = require 'rosavim.config.toggles'

local KEYWORDS = { 'TODO', 'FIX', 'HACK', 'WARN', 'PERF', 'NOTE', 'TEST' }

-- Personal task files that should surface in the todo listings even when they
-- are git-ignored. Matched case-insensitively (todo.md, TODO.md, Tarefas.md …).
-- Single source of truth for both the Snacks picker and the :TodoTrouble search.
M.allowed_names = { 'todo', 'todos', 'task', 'tasks', 'tarefa', 'tarefas' }

-- Turn a lowercase name into a case-insensitive ripgrep glob char class,
-- e.g. 'todo' -> '[Tt][Oo][Dd][Oo]'.
local function charclass(name)
  local out = {}
  for i = 1, #name do
    local c = name:sub(i, i)
    out[#out + 1] = '[' .. c:upper() .. c:lower() .. ']'
  end
  return table.concat(out)
end

-- ripgrep glob patterns matching the allowed task-file names anywhere in the
-- tree, case-insensitive on both name and extension, e.g.
-- '**/[Tt][Oo][Dd][Oo].[Mm][Dd]'.
function M.whitelist_patterns()
  local pats = {}
  for _, name in ipairs(M.allowed_names) do
    pats[#pats + 1] = '**/' .. charclass(name) .. '.[Mm][Dd]'
  end
  return pats
end

-- ripgrep args for the "second pass" of the Snacks todo picker: whitelist the
-- allowed task files first, then re-apply the caller's directory excludes AFTER
-- them so the excludes keep winning (ripgrep: the last matching same-family
-- glob wins, and `--glob`/`--iglob` do NOT compose across families). Paired
-- with `ignored = true` (--no-ignore) so git-ignored task files surface while
-- everything else still honours .gitignore.
function M.pass2_args(exclude)
  local args = {}
  for _, pat in ipairs(M.whitelist_patterns()) do
    args[#args + 1] = '--glob'
    args[#args + 1] = pat
  end
  for _, e in ipairs(exclude or {}) do
    args[#args + 1] = '--glob'
    args[#args + 1] = '!' .. e
  end
  return args
end

-- Build the bash wrapper that :TodoTrouble/:TodoQuickFix/:TodoLocList use as
-- their `rg` command: pass 1 respects .gitignore, pass 2 force-includes the
-- git-ignored task files via the whitelist (still honouring the dir excludes
-- passed by the plugin), and the two outputs are merged + de-duplicated.
local function wrapper_content()
  local wl = {}
  for _, pat in ipairs(M.whitelist_patterns()) do
    wl[#wl + 1] = "  --glob '" .. pat .. "'"
  end
  return table.concat({
    '#!/usr/bin/env bash',
    '# GENERATED by rosavim.rosa_plugins.rosatodo — do not edit by hand.',
    '# ripgrep wrapper for todo-comments.nvim:',
    '#   pass 1: normal search (respects .gitignore)',
    '#   pass 2: force-includes git-ignored task files (todo/task/tarefas, any',
    '#           case) via a whitelist, still honouring the caller dir excludes',
    '# Outputs are concatenated and de-duplicated line-by-line.',
    'WL=(',
    table.concat(wl, '\n'),
    ')',
    '{',
    '  rg "$@"',
    '  rg --no-ignore "${WL[@]}" "$@"',
    "} | awk '!seen[$0]++'",
    '',
  }, '\n')
end

-- Ensure the wrapper script exists (regenerated when M.allowed_names changes)
-- and is executable, then return its path.
function M.rg_wrapper()
  local path = vim.fn.stdpath 'config' .. '/rosa_bin/rosatodo-rg'
  local want = wrapper_content()
  local have
  local fd = io.open(path, 'r')
  if fd then
    have = fd:read '*a'
    fd:close()
  end
  if have ~= want then
    vim.fn.mkdir(vim.fn.fnamemodify(path, ':h'), 'p')
    local out = io.open(path, 'w')
    if out then
      out:write(want)
      out:close()
    end
  end
  pcall((vim.uv or vim.loop).fs_chmod, path, 493) -- 0755
  return path
end

function M.ensure_loaded()
  if not package.loaded['todo-comments'] then
    require('lazy').load { plugins = { 'todo-comments.nvim' } }
  end
end

function M.force_fg()
  for _, kw in ipairs(KEYWORDS) do
    local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = 'TodoBg' .. kw })
    if ok and hl.bg then
      vim.api.nvim_set_hl(0, 'TodoBg' .. kw, { bg = hl.bg, fg = '#111111', bold = true })
    end
  end
end

function M.apply_style()
  local ok, cfg = pcall(require, 'todo-comments.config')
  if not ok or not cfg.options or not cfg.options.highlight then
    return
  end
  local bg = toggles.get 'todo_comments_bg'
  local fg = toggles.get 'todo_comments_fg'
  cfg.options.highlight.keyword = bg and 'wide' or (fg and 'fg' or '')
  cfg.options.highlight.after = (bg or fg) and 'fg' or ''
  cfg.options.signs = (bg or fg) and true or false
  M.force_fg()
  if toggles.get 'todo_comments' then
    local hl = require 'todo-comments.highlight'
    hl.stop()
    hl.start()
    for _, win in ipairs(vim.api.nvim_list_wins()) do
      if vim.api.nvim_win_is_valid(win) then
        local buf = vim.api.nvim_win_get_buf(win)
        if vim.api.nvim_buf_is_valid(buf) then
          hl.attach(win)
          hl.invalidate(buf, 0, -1)
        end
      end
    end
  end
end

local function ready()
  local ok, cfg = pcall(require, 'todo-comments.config')
  return ok and cfg.options and cfg.options.highlight ~= nil
end

function M.restore()
  local function try(attempt)
    if ready() then
      M.apply_style()
      if not toggles.get 'todo_comments' then
        require('todo-comments').disable()
      end
    elseif attempt < 100 then
      vim.defer_fn(function()
        try(attempt + 1)
      end, 20)
    end
  end
  try(0)
end

function M.set_enabled(state)
  M.ensure_loaded()
  toggles.set('todo_comments', state)
  if state then
    M.apply_style()
  else
    require('todo-comments').disable()
  end
end

function M.set_bg(state)
  M.ensure_loaded()
  toggles.set('todo_comments_bg', state)
  if state then
    toggles.set('todo_comments_fg', false)
  end
  M.apply_style()
end

function M.set_fg(state)
  M.ensure_loaded()
  toggles.set('todo_comments_fg', state)
  if state then
    toggles.set('todo_comments_bg', false)
  end
  M.apply_style()
end

return M
